safe:        false
port: 4000

source:      .
destination: ./_site
plugins_dir:     ./_plugins
encoding: UTF-8

future:      true
lsi:         false
highlighter:    pygments
markdown:    kramdown
permalink:   pretty

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []

exclude:      ['Rakefile']
